#!/bin/bash

file_path=/home/clliao/workspace/python/weather_prediction/ensemble_regression/main_PM2_5.py
training_year=2014-2015
testing_year=2015-2015
training_duration=1/1-11/30
testing_duration=12/1-12/31
is_training=True
for month in 1
do
    if [ $month == "1" ]; then
        echo test_month_"$month"
        training_year=2014-2016
        testing_year=2017-2017
        training_duration=1/1-12/31
        testing_duration=1/1-1/31
    elif [ $month == "2" ]; then
        echo test_month_"$month"
        training_year=2014-2015
        testing_year=2015-2015
        training_duration=1/1-1/31
        testing_duration=2/1-2/28
    elif [ $month == "4" ]; then
        echo test_month_"$month"
        training_year=2014-2015
        testing_year=2015-2015
        training_duration=1/1-3/31
        testing_duration=4/1-4/30
    elif [ $month == "7" ]; then
        echo test_month_"$month"
        training_year=2014-2015
        testing_year=2015-2015
        training_duration=1/1-6/30
        testing_duration=7/1-7/31
    elif [ $month == "10" ]; then
        echo test_month_"$month"
        training_year=2014-2015
        testing_year=2015-2015
        training_duration=1/1-9/30
        testing_duration=10/1-10/31
    elif [ $month == "11" ]; then
        echo test_month_"$month"
        training_year=2014-2015
        testing_year=2015-2015
        training_duration=1/1-10/31
        testing_duration=11/1-11/30
    elif [ $month == "12" ]; then
        echo test_month_"$month"
        training_year=2014-2015
        testing_year=2015-2015
        training_duration=1/1-11/30
        testing_duration=12/1-12/31
    else
        echo month error
    fi
    local=宜蘭
    city=宜蘭
    for site in 冬山 宜蘭
    do
        for interval in 1 6 12
        do
            echo $file_path
            python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
        done
    done
    local=花東
    city=花蓮
    for site in 花蓮
    do
        for interval in 1 6 12
        do
            echo $file_path
            python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
        done
    done
    city=台東
    for site in 臺東
    do
        for interval in 1 6 12
        do
            echo $file_path
            python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
        done
    done
    local=西部離島
    city=金門
    for site in 金門
    do
        for interval in 1 6 12
        do
            echo $file_path
            python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
        done
    done
    city=連江
    for site in 馬祖
    do
        for interval in 1 6 12
        do
            echo $file_path
            python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
        done
    done
    city=澎湖
    for site in 馬公
    do
        for interval in 1 6 12
        do
            echo $file_path
            python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
        done
    done
done
