#!/bin/bash

file_path=/media/clliao/006a3168-df49-4b0a-a874-891877a88870/clliao/workspace/python/weather_prediction/ensemble_regression/rnn_model.py
training_year=2014-2016
testing_year=2016-2016
training_duration=1/1-10/31
testing_duration=11/15-12/31
is_training=True
local=北部
city=新北
for site in 板橋 林口
do
    for interval in 24
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
city=台北
for site in 古亭 萬華
do
    for interval in 24
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
local=竹苗
city=新竹
for site in 新竹
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
city=苗栗
for site in 苗栗
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
local=中部
city=台中
for site in 忠明  西屯
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
city=彰化
for site in 彰化
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
local=雲嘉南
city=嘉義
for site in 嘉義
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
city=雲林
for site in 斗六
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
local=高屏
city=高雄
for site in 左營 小港
do
    for interval in 1 6 12
    do
        echo $file_path
        python $file_path $local $city $site $training_year $testing_year $training_duration $testing_duration $interval $is_training
    done
done
